version: '3.7'

services:
  postgres:
    container_name: fastify_postgres
    image: bitnami/postgresql:latest
    ports:
      - '5438:5432'
    environment:
      - POSTGRES_USER=fastify
      - POSTGRES_PASSWORD=fastify
      - POSTGRES_DB=fastify
    volumes:
      - fastify_pg_data:/bitnami/postgresql

  redis:
    container_name: fastify_redis
    image: bitnami/redis:latest
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - fastify_redis_data:/bitnami/redis

volumes:
  fastify_pg_data:
  fastify_redis_data: