version: '3'

services:
  web:
    container_name: nextjs-docker-postgres
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_USER: nextjs-docker-postgres
      POSTGRES_PASSWORD: nextjs-docker-postgres
      POSTGRES_DB: nextjs-docker-postgres
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}?schema=public
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always
    ports:
      - "3000:3000"
  db:
    image: postgres:15-alpine
    ports:
      - "5435:5432"
    restart: always
    environment:
      - POSTGRES_DB=nextjs-docker-postgres
      - POSTGRES_USER=nextjs-docker-postgres
      - POSTGRES_PASSWORD=nextjs-docker-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: 